// GENERAL CONST
export const NAVIGATE = 'NAVIGATE'
export const SEND_HTTP_REQUEST = 'SEND_HTTP_REQUEST'
export const INITIALIZATION_SUCCESS = 'INITIALIZATION_SUCCESS'
export const UPDATE_TOP_UP_DETAILS = 'UPDATE_TOP_UP_DETAILS'
export const SUBMIT_TOP_UP_REQUEST_RESPONSE = 'SUBMIT_TOP_UP_REQUEST_RESPONSE'
export const ADD_USER_BANK = 'ADD_USER_BANK'
export const SELECT_BANK_FOR_ACTION = 'SELECT_BANK_FOR_ACTION'
