// GENERAL CONST
export const NAVIGATE_FLOW_TYPE = 'NAVIGATE_FLOW_TYPE'
export const NAVIGATE_SCREEN_IN_FLOW_TYPE = 'NAVIGATE_SCREEN_IN_FLOW_TYPE'
export const SEND_HTTP_REQUEST = 'SEND_HTTP_REQUEST'
export const INITIALIZATION_SUCCESS = 'INITIALIZATION_SUCCESS'

// BANK ACCOUNT-RELATED CONST
export const UPDATE_SEARCH_FILTER = 'UPDATE_SEARCH_FILTER'
export const INIT_NEW_BANK_ACCOUNT = 'INIT_NEW_BANK_ACCOUNT'
export const UPDATE_BANK_ACCOUNT_DETAILS = 'UPDATE_BANK_ACCOUNT_DETAILS'
export const SUBMIT_NEW_BANK_ACCOUNT_RESPONSE = 'SUBMIT_NEW_BANK_ACCOUNT_RESPONSE'
export const DELETE_BANK_ACCOUNT_RESPONSE = 'DELETE_BANK_ACCOUNT_RESPONSE'

// WITHDRAWAL CONST
export const INIT_WITHDRAWAL_FORM = 'INIT_WITHDRAWAL_FORM'
export const UPDATE_WITHDRAWAL_DETAILS = 'UPDATE_WITHDRAWAL_DETAILS'
export const FETCH_WITHDRAWAL_LIMITS_SUCCESS = 'FETCH_WITHDRAWAL_LIMITS_SUCCESS'
export const FETCH_FEE_BREAKDOWN_SUCCESS = 'FETCH_FEE_BREAKDOWN_SUCCESS'
export const FETCH_FEE_BREAKDOWN_ERROR = 'FETCH_FEE_BREAKDOWN_ERROR'
export const SUBMIT_WITHDRAWAL_SUCCEESS = 'SUBMIT_WITHDRAWAL_SUCCEESS'
export const SUBMIT_WITHDRAWAL_ERROR = 'SUBMIT_WITHDRAWAL_ERROR'

// TOP-UP CONST
export const UPDATE_TOP_UP_DETAILS = 'UPDATE_TOP_UP_DETAILS'
export const SUBMIT_TOP_UP_REQUEST_SUCCESS = 'SUBMIT_TOP_UP_REQUEST_SUCCESS'
export const SUBMIT_TOP_UP_REQUEST_ERROR = 'SUBMIT_TOP_UP_REQUEST_ERROR'



export const SELECT_BANK_FOR_ACTION = 'SELECT_BANK_FOR_ACTION'
export const CONFIRM_PAYMENT_RESPONSE = 'CONFIRM_PAYMENT_RESPONSE'





// UNUSED
// export const SET_ERROR_MSG = 'SET_ERROR_MSG'
// export const CLEAR_ERROR_MSG = 'CLEAR_ERROR_MSG'
// export const SET_CURRENT_BANK_ACCOUNT = 'SET_CURRENT_BANK_ACCOUNT'



// getWithdrawalFeesBreakdown
// getWithdrawalLimits
// createWithdrawalRequest: bankId,amount, express
