// GENERAL CONST
export const NAVIGATE = 'NAVIGATE'
export const SEND_HTTP_REQUEST = 'SEND_HTTP_REQUEST'
export const INITIALIZATION_SUCCESS = 'INITIALIZATION_SUCCESS'
export const UPDATE_SEARCH_FILTER = 'UPDATE_SEARCH_FILTER'

// BANK ACCOUNT-RELATED CONST
export const INIT_NEW_BANK_ACCOUNT = 'INIT_NEW_BANK_ACCOUNT'
export const UPDATE_BANK_ACCOUNT_DETAILS = 'UPDATE_BANK_ACCOUNT_DETAILS'
export const SUBMIT_NEW_BANK_ACCOUNT_RESPONSE = 'SUBMIT_NEW_BANK_ACCOUNT_RESPONSE'

// UNUSED
// export const SET_ERROR_MSG = 'SET_ERROR_MSG'
// export const CLEAR_ERROR_MSG = 'CLEAR_ERROR_MSG'
// export const SET_CURRENT_BANK_ACCOUNT = 'SET_CURRENT_BANK_ACCOUNT'
