// GENERAL CONST
export const NAVIGATE = 'NAVIGATE'
export const SEND_HTTP_REQUEST = 'SEND_HTTP_REQUEST'
export const INITIALIZATION_SUCCESS = 'INITIALIZATION_SUCCESS'
export const OPEN_MODAL = 'OPEN_MODAL'
export const CLOSE_MODAL = 'CLOSE_MODAL'
