// GENERAL CONST
export const NAVIGATE = 'NAVIGATE'
export const SEND_HTTP_REQUEST = 'SEND_HTTP_REQUEST'
export const INITIALIZATION_SUCCESS = 'INITIALIZATION_SUCCESS'
export const CONFIRM_PAYMENT_RESPONSE = 'CONFIRM_PAYMENT_RESPONSE'
